
import Head from 'next/head'
import Image from 'next/image'
import { useEffect,useState } from 'react'
import Grid from '@mui/material/Grid';
import Card from "../components/Card"
import { Button } from '@mui/material';
// https://random-data-api.com/api/code/random_code

  
export default function Home({posts,deferredPrompt,setDeferredPrompt}) {

  const [latitude,setLatitude] = useState()
  const [longitude,setLongitude] = useState()
  const handleClick = () => {
    if (deferredPrompt) {

    deferredPrompt.prompt();

    deferredPrompt.userChoice.then(function(choiceResult) {
      console.log(choiceResult.outcome);

      if (choiceResult.outcome === 'dismissed') {
        console.log('User cancelled installation');
      } else {
        console.log('User added to home screen');
      }
    });

    setDeferredPrompt(null)
  }
  }

  useEffect(() => {
    console.log(posts)
    
  }, [posts])

  const handleLocation = () => {
      if(!('geolocation' in navigator)) {
        return;
      }

      navigator.geolocation.getCurrentPosition(function(position) {
        console.log(position.coords)
        setLatitude(position.coords.latitude)
        setLongitude(position.coords.longitude)
      },err => alert(err),{
        timeout:7000
      })
  }
  const BackgroundSync = () => {
     if ('serviceWorker' in navigator && 'SyncManager' in window) {
    navigator.serviceWorker.ready
      .then(function(sw) {
            return sw.sync.register('sync-new-posts');
      });
  } else {
    fetch('https://random-data-api.com/api/code/random_code')
      .then(response => response.json())
      .then(data => {
        console.log("[Background sync]  ",data)
      })
  }
  }
  

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="manifest" href="/manifest.json" />
      </Head>

  

      <Button onClick={handleClick} variant="outlined">INSTALL</Button>
      <Button onClick={BackgroundSync} variant="outlined">BACKGROUND SYNC</Button>
      <Button onClick={handleLocation} variant="outlined">GET LOCATION</Button>

      
<Grid container spacing={{ xs: 2, md: 3 }} columns={{ xs: 4, sm: 8, md: 12 }}>
  {posts.map((post,index) => (
    <Grid item xs={2} sm={4} md={4} key={index}>
      <Card data={post} />  
    </Grid>
  ))}

</Grid>
    {latitude && (
      <h1>latitude :- {latitude}</h1>
    )}
    {longitude && (
      <h1>longitude :- {longitude}</h1>
    )}



      </div>
  )
}

export async function getServerSideProps() {
  // Fetch data from external API
  // const res = await fetch(`https://pwa-db-a5baf-default-rtdb.asia-southeast1.firebasedatabase.app/posts.json`)
  // const data = await res.json()
  const FAKE_DATA = [
    {
      id: "2022-08-02T08:36:41.966Z",
    "image": "https://images.unsplash.com/photo-1659298136703-f5880b90b174?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2128&q=80",
    "location": "madsnb das",
    "title": "kadjssda"
    },
    {
    "id": "2022-08-05T12:05:32.956Z",
    "image": "https://firebasestorage.googleapis.com/v0/b/pwa-db-a5baf.appspot.com/o/images%2Fastronaut-in-space-compressor.png?alt=media&token=55b9444a-f75d-4c5c-8e2b-4b930abe1a2f",
    "location": "dsasa",
    "title": "Ishaan"
  },
  {
      id: "2022-08-02T08:36:41.966Z",
    "image": "https://images.unsplash.com/photo-1659298136703-f5880b90b174?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2128&q=80",
    "location": "madsnb das",
    "title": "kadjssda"
    },
    {
    "id": "2022-08-05T12:05:32.956Z",
    "image": "https://firebasestorage.googleapis.com/v0/b/pwa-db-a5baf.appspot.com/o/images%2Fastronaut-in-space-compressor.png?alt=media&token=55b9444a-f75d-4c5c-8e2b-4b930abe1a2f",
    "location": "dsasa",
    "title": "Ishaan"
  },
  ]

  // Pass data to the page via props
  return { props: { posts:FAKE_DATA } }
}
